# Generated by Django 2.2.16 on 2022-09-05 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_auto_20220829_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AddField(
            model_name='group',
            name='author',
            field=models.ForeignKey(default='1', help_text='Автор группы', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор группы'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Открытая или закрытая группа', verbose_name='Открытая или закрытая группа'),
        ),
    ]
