# Generated by Django 2.2.28 on 2022-09-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220905_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='author',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_open',
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='Короткий адрес группы', unique=True, verbose_name='Короткий адрес группы'),
        ),
    ]
